<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="TCLIN53" failures="1" tests="1" name="Test(failed)" time="0.043" errors="0" timestamp="2023-04-28T10:31:35 IST">
  <testcase classname="RerunFailedcases.RerunUsingTestNG" name="Testcase2" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at RerunFailedcases.RerunUsingTestNG.Testcase2(RerunUsingTestNG.java:15)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- Testcase2 -->
  <testcase classname="RerunFailedcases.RerunUsingTestNG" name="Testcase1" time="0.0">
    <ignored/>
  </testcase> <!-- Testcase1 -->
</testsuite> <!-- Test(failed) -->
