<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="TCLIN53" failures="2" tests="10" name="Test" time="0.067" errors="0" timestamp="2023-04-28T12:17:24 IST">
  <testcase classname="RerunFailedcases.RerunUsingTestNG" name="Testcase1" time="0.011">
    <skipped/>
  </testcase> <!-- Testcase1 -->
  <testcase classname="RerunFailedcases.RerunUsingTestNG" name="Testcase2" time="0.011">
    <skipped/>
  </testcase> <!-- Testcase2 -->
  <testcase classname="RerunFailedcases.RerunUsingTestNG" name="Testcase2" time="0.002">
    <skipped/>
  </testcase> <!-- Testcase2 -->
  <testcase classname="RerunFailedcases.RerunUsingTestNG" name="Testcase1" time="0.001">
    <skipped/>
  </testcase> <!-- Testcase1 -->
  <testcase classname="RerunFailedcases.RerunUsingTestNG" name="Testcase1" time="0.002">
    <skipped/>
  </testcase> <!-- Testcase1 -->
  <testcase classname="RerunFailedcases.RerunUsingTestNG" name="Testcase2" time="0.001">
    <skipped/>
  </testcase> <!-- Testcase2 -->
  <testcase classname="RerunFailedcases.RerunUsingTestNG" name="Testcase1" time="0.002">
    <skipped/>
  </testcase> <!-- Testcase1 -->
  <testcase classname="RerunFailedcases.RerunUsingTestNG" name="Testcase2" time="0.001">
    <skipped/>
  </testcase> <!-- Testcase2 -->
  <testcase classname="RerunFailedcases.RerunUsingTestNG" name="Testcase1" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at RerunFailedcases.RerunUsingTestNG.Testcase1(RerunUsingTestNG.java:10)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- Testcase1 -->
  <testcase classname="RerunFailedcases.RerunUsingTestNG" name="Testcase2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at RerunFailedcases.RerunUsingTestNG.Testcase2(RerunUsingTestNG.java:15)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- Testcase2 -->
</testsuite> <!-- Test -->
